/**
 * Firestore service with typed CRUD operations for ChannelSignal entities.
 */

import {
  collection,
  doc,
  addDoc,
  getDoc,
  getDocs,
  updateDoc,
  query,
  where,
  orderBy,
  Timestamp,
  DocumentReference,
  CollectionReference,
} from 'firebase/firestore';
import { db } from './firebase';
import type {
  Deal,
  DealData,
  Organization,
  OrganizationData,
  DealStatus,
  CreateDealInput,
  CreateOrganizationInput,
} from '../types/channelsignal';

// Collection names
const COLLECTIONS = {
  DEALS: 'deals',
  ORGANIZATIONS: 'organizations',
} as const;

/**
 * Converts Firestore Timestamps to JS Dates in an object.
 */
function convertTimestamps<T extends Record<string, unknown>>(data: T): T {
  const result = { ...data };
  for (const key of Object.keys(result)) {
    const value = result[key];
    if (value instanceof Timestamp) {
      (result as Record<string, unknown>)[key] = value.toDate();
    }
  }
  return result;
}

/**
 * Get a typed collection reference.
 */
function getDealsCollection(): CollectionReference<DealData> {
  return collection(db, COLLECTIONS.DEALS) as CollectionReference<DealData>;
}

function getOrganizationsCollection(): CollectionReference<OrganizationData> {
  return collection(db, COLLECTIONS.ORGANIZATIONS) as CollectionReference<OrganizationData>;
}

// ============================================================================
// Deal Operations
// ============================================================================

/**
 * Creates a new deal in Firestore.
 *
 * @param deal - Deal data without id (will be generated by Firestore)
 * @returns The created deal with its generated ID
 */
export async function createDeal(deal: CreateDealInput): Promise<Deal> {
  const now = new Date();
  const dealData: DealData = {
    ...deal,
    extractedAt: now,
    updatedAt: now,
  };

  const docRef = await addDoc(getDealsCollection(), dealData as DealData);

  return {
    id: docRef.id,
    ...dealData,
  };
}

/**
 * Retrieves all deals for a specific organization.
 *
 * @param orgId - Organization ID to filter by
 * @returns Array of deals belonging to the organization, ordered by extraction date (newest first)
 */
export async function getDealsByOrg(orgId: string): Promise<Deal[]> {
  const dealsRef = getDealsCollection();
  const q = query(
    dealsRef,
    where('organizationId', '==', orgId),
    orderBy('extractedAt', 'desc')
  );

  const snapshot = await getDocs(q);

  return snapshot.docs.map((docSnap) => {
    const data = convertTimestamps(docSnap.data() as Record<string, unknown>) as DealData;
    return {
      id: docSnap.id,
      ...data,
    } as Deal;
  });
}

/**
 * Retrieves a single deal by ID.
 *
 * @param dealId - The deal document ID
 * @returns The deal if found, null otherwise
 */
export async function getDealById(dealId: string): Promise<Deal | null> {
  const docRef = doc(db, COLLECTIONS.DEALS, dealId) as DocumentReference<DealData>;
  const docSnap = await getDoc(docRef);

  if (!docSnap.exists()) {
    return null;
  }

  const data = convertTimestamps(docSnap.data() as Record<string, unknown>) as DealData;
  return {
    id: docSnap.id,
    ...data,
  };
}

/**
 * Updates the status of a deal.
 *
 * @param dealId - The deal document ID
 * @param status - The new status to set
 */
export async function updateDealStatus(dealId: string, status: DealStatus): Promise<void> {
  const docRef = doc(db, COLLECTIONS.DEALS, dealId);
  await updateDoc(docRef, {
    status,
    updatedAt: new Date(),
  });
}

/**
 * Updates deal fields.
 *
 * @param dealId - The deal document ID
 * @param updates - Partial deal data to update
 */
export async function updateDeal(
  dealId: string,
  updates: Partial<Omit<Deal, 'id' | 'extractedAt'>>
): Promise<void> {
  const docRef = doc(db, COLLECTIONS.DEALS, dealId);
  await updateDoc(docRef, {
    ...updates,
    updatedAt: new Date(),
  });
}

// ============================================================================
// Organization Operations
// ============================================================================

/**
 * Creates a new organization in Firestore.
 *
 * @param org - Organization data without id (will be generated by Firestore)
 * @returns The created organization with its generated ID
 */
export async function createOrganization(org: CreateOrganizationInput): Promise<Organization> {
  const now = new Date();
  const orgData: OrganizationData = {
    ...org,
    createdAt: now,
    updatedAt: now,
  };

  const docRef = await addDoc(getOrganizationsCollection(), orgData as OrganizationData);

  return {
    id: docRef.id,
    ...orgData,
  };
}

/**
 * Retrieves an organization by ID.
 *
 * @param orgId - The organization document ID
 * @returns The organization if found, null otherwise
 */
export async function getOrganizationById(orgId: string): Promise<Organization | null> {
  const docRef = doc(db, COLLECTIONS.ORGANIZATIONS, orgId) as DocumentReference<OrganizationData>;
  const docSnap = await getDoc(docRef);

  if (!docSnap.exists()) {
    return null;
  }

  const data = convertTimestamps(docSnap.data() as Record<string, unknown>) as OrganizationData;
  return {
    id: docSnap.id,
    ...data,
  };
}

/**
 * Looks up an organization by its BCC address.
 *
 * @param bccAddress - The unique BCC email address
 * @returns The organization if found, null otherwise
 */
export async function getOrgByBccAddress(bccAddress: string): Promise<Organization | null> {
  const orgsRef = getOrganizationsCollection();
  const q = query(orgsRef, where('bccAddress', '==', bccAddress));

  const snapshot = await getDocs(q);

  if (snapshot.empty) {
    return null;
  }

  // BCC addresses should be unique, so we take the first match
  const docSnap = snapshot.docs[0];
  const data = convertTimestamps(docSnap.data() as Record<string, unknown>) as OrganizationData;

  return {
    id: docSnap.id,
    ...data,
  };
}

/**
 * Updates organization fields.
 *
 * @param orgId - The organization document ID
 * @param updates - Partial organization data to update
 */
export async function updateOrganization(
  orgId: string,
  updates: Partial<Omit<Organization, 'id' | 'createdAt'>>
): Promise<void> {
  const docRef = doc(db, COLLECTIONS.ORGANIZATIONS, orgId);
  await updateDoc(docRef, {
    ...updates,
    updatedAt: new Date(),
  });
}

/**
 * Gets deals count for an organization.
 *
 * @param orgId - Organization ID
 * @returns Number of deals in the organization
 */
export async function getDealsCountByOrg(orgId: string): Promise<number> {
  const deals = await getDealsByOrg(orgId);
  return deals.length;
}
